### ISSUE TITLE
F-362 Tras actualizar execjs, error al ejecutar "RAILS_ENV=production bin/railsp assets:precompile" genera "JSON::ParserError: 439: unexpected token at '{"line":82,"column":32,"so'"

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/cor1440_cinep#32]
Al ejecutar con traza. 
```
$ RAILS_ENV=production bin/railsp assets:precompile --trace
...
rails aborted!                                                                                                                                                  
JSON::ParserError: 439: unexpected token at '{"line":82,"column":32,"so'                                                                                        
/usr/local/lib/ruby/3.0/json/common.rb:217:in `parse'                                                                                                           
/usr/local/lib/ruby/3.0/json/common.rb:217:in `parse'                                                                                                           
/var/www/bundler/ruby/3.0/gems/execjs-2.8.0/lib/execjs/external_runtime.rb:68:in `extract_result'                                                               
/var/www/bundler/ruby/3.0/gems/execjs-2.8.0/lib/execjs/external_runtime.rb:39:in `exec'                                                                         
/var/www/bundler/ruby/3.0/gems/execjs-2.8.0/lib/execjs/external_runtime.rb:21:in `eval'                                                                         
/var/www/bundler/ruby/3.0/gems/execjs-2.8.0/lib/execjs/external_runtime.rb:46:in `call'                                                                         
/var/www/bundler/ruby/3.0/gems/coffee-script-2.4.1/lib/coffee_script.rb:78:in `compile'                                                                         
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/coffee_script_processor.rb:24:in `block in call'                                                   
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/cache.rb:92:in `fetch'                                                                             
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/coffee_script_processor.rb:23:in `call'                                                            
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:84:in `call_processor'                                                          
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:66:in `block in call_processors'                                                
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:65:in `reverse_each'                                                            
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:65:in `call_processors'                                                         
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:22:in `block in <class:CompositeProcessor>'                                     
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:33:in `call'                                                                    
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:84:in `call_processor'                                                          
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:66:in `block in call_processors'                                                
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:65:in `reverse_each'                                                            
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:65:in `call_processors'                                                         
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/loader.rb:182:in `load_from_unloaded'                                                              
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/loader.rb:59:in `block in load'                                                                    
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/loader.rb:337:in `fetch_asset_from_dependency_cache'                                               
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/loader.rb:43:in `load'                                                                             
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/cached_environment.rb:44:in `load'                                                                 
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/bundle.rb:41:in `block in call'                                                                    
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/utils.rb:167:in `dfs'                                                                              
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/bundle.rb:42:in `call'                                                                             
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:84:in `call_processor'                                                          
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:66:in `block in call_processors'                                                
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:65:in `reverse_each'                                                            
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:65:in `call_processors'                                                         
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/loader.rb:182:in `load_from_unloaded'                                                              
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/loader.rb:59:in `block in load'                                                                    
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/loader.rb:337:in `fetch_asset_from_dependency_cache'                                               
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/loader.rb:43:in `load'                                                                             
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/cached_environment.rb:44:in `load'                                                                 
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/bundle.rb:32:in `block in call'                                                                    
/usr/local/lib/ruby/3.0/set.rb:344:in `each_key'                                                                                                                
/usr/local/lib/ruby/3.0/set.rb:344:in `each'                                                                                                                    
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/bundle.rb:31:in `call'                                                                             
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:84:in `call_processor'                                                          
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:66:in `block in call_processors'                                                
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:65:in `reverse_each'                                                            
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:65:in `call_processors'                                                         
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/loader.rb:182:in `load_from_unloaded'                                                              
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/loader.rb:59:in `block in load'                                                                    
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/loader.rb:337:in `fetch_asset_from_dependency_cache'                                               
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/loader.rb:43:in `load'                                                                             
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/cached_environment.rb:44:in `load'                                                                 
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/base.rb:81:in `find_asset'                                                                         
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/base.rb:88:in `find_all_linked_assets'                                                             
/var/www/bundler/ruby/3.0/gems/sprockets-4.0.2/lib/sprockets/manifest.rb:125:in `block (2 levels) in find'                                                      
/var/www/bundler/ruby/3.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'                     
/var/www/bundler/ruby/3.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:41:in `block in synchronize'       
/var/www/bundler/ruby/3.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'                
/var/www/bundler/ruby/3.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'                
/var/www/bundler/ruby/3.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:19:in `execute'                              
/var/www/bundler/ruby/3.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/promise.rb:563:in `block in realize'                                        
/var/www/bundler/ruby/3.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:363:in `run_task'                     
/var/www/bundler/ruby/3.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `block (3 levels) in create_wor
ker'                                                                                                                                                            
/var/www/bundler/ruby/3.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `loop'                         
/var/www/bundler/ruby/3.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `block (2 levels) in create_wor
ker'                                                                                                                                                            
/var/www/bundler/ruby/3.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `catch'                        
/var/www/bundler/ruby/3.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block in create_worker'       
Tasks: TOP => assets:precompile                                                                                                                                 
```

**Comment by vtamara** [comment]
Examinando el error se encuentra que execjs genera incompleta la salida de una llamada a un js que compila una fuente coffescript.

Se adjunta el archivo javscript de ejemplo
[example_compile_coffescript.zip](https://github.com/pasosdeJesus/cor1440_cinep/files/6465308/example_compile_coffescript.zip)

**Comment by vtamara** [comment]
De hecho al extraer de execjs la parte que realiza el llamado a node y que genera el resultado se obtiene el mismo error.

```
# De https://github.com/rails/execjs/blob/master/lib/execjs/external_runtime.rb

require 'json'

def binary
  'node'
end

@popen_options = {}
@popen_options[:external_encoding] = 'UTF-8'
@popen_options[:internal_encoding] = ::Encoding.default_internal || 'UTF-8'


def exec_runtime(filename)
#  byebug
  io = IO.popen(binary.split(' ') << filename, **(@popen_options.merge({err: [:child, :out]})))
  output = io.read
  io.close

  if $?.success?
    output
  else
    raise exec_runtime_error(output)
  end
end

output = exec_runtime('example_compile_coffescript.js')
puts ::JSON.parse(output, create_additions: false)
```

Notar que con el

**Comment by vtamara** [comment]
Mientras no se mejore la implementación de node en su implementación con tuberías nos parece que execjs no debería usar tuberías para procesar salida de node, sino más bien redirigir la salida a un archivo y después leer el archivo (análogo a como se hace en el caso de Windows en el mismo archivo <https://github.com/rails/execjs/blob/master/lib/execjs/external_runtime.rb>.

Esta ruta se propone en la rama `exec-reliable` de <https://github.com/vtamara/execjs/tree/exec-reliable>
